
package client.ejb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServerMainService", targetNamespace = "http://Server/", wsdlLocation = "http://localhost:456/runCal?wsdl")
public class ServerMainService
    extends Service
{

    private final static URL SERVERMAINSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVERMAINSERVICE_EXCEPTION;
    private final static QName SERVERMAINSERVICE_QNAME = new QName("http://Server/", "ServerMainService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:456/runCal?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVERMAINSERVICE_WSDL_LOCATION = url;
        SERVERMAINSERVICE_EXCEPTION = e;
    }

    public ServerMainService() {
        super(__getWsdlLocation(), SERVERMAINSERVICE_QNAME);
    }

    public ServerMainService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVERMAINSERVICE_QNAME, features);
    }

    public ServerMainService(URL wsdlLocation) {
        super(wsdlLocation, SERVERMAINSERVICE_QNAME);
    }

    public ServerMainService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVERMAINSERVICE_QNAME, features);
    }

    public ServerMainService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServerMainService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServerMain
     */
    @WebEndpoint(name = "ServerMainPort")
    public ServerMain getServerMainPort() {
        return super.getPort(new QName("http://Server/", "ServerMainPort"), ServerMain.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServerMain
     */
    @WebEndpoint(name = "ServerMainPort")
    public ServerMain getServerMainPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://Server/", "ServerMainPort"), ServerMain.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVERMAINSERVICE_EXCEPTION!= null) {
            throw SERVERMAINSERVICE_EXCEPTION;
        }
        return SERVERMAINSERVICE_WSDL_LOCATION;
    }

}
