
package client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebService", targetNamespace = "http://webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "HelloWord")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "HelloWord", targetNamespace = "http://webservice/", className = "client.HelloWord")
    @ResponseWrapper(localName = "HelloWordResponse", targetNamespace = "http://webservice/", className = "client.HelloWordResponse")
    @Action(input = "http://webservice/HelloWebService/HelloWordRequest", output = "http://webservice/HelloWebService/HelloWordResponse")
    public String helloWord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
